"""Post-build payload corrections and freshness metadata.

build.py intentionally owns model fitting and prediction generation. This
small finalization step owns data that must be current-season-only, especially
league tables, and attaches refresh health generated by refresh.py.

Run after model/build.py and before model/site.py.
"""

import csv
import json
import os
import sys
from datetime import datetime

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import names as N

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
PAYLOAD_PATH = os.path.join(DATA, "payload.json")
STATUS_PATH = os.path.join(DATA, "refresh_status.json")

ZONES = {
    "E0": (4, 3), "E1": (2, 3), "D1": (4, 2), "F1": (3, 2), "N1": (2, 2),
    "SP1": (4, 3), "I1": (4, 3),
    "USA": (0, 0), "MEX": (0, 0), "BRA": (0, 0), "ARG": (0, 0), "JPN": (0, 0),
}


def load_current_rows(div):
    """Load one division's current-season results in build.py's internal shape."""
    fname = N.CURRENT_STEM.get(div)
    if not fname:
        return []
    path = os.path.join(DATA, fname)
    if not os.path.exists(path) or os.path.getsize(path) == 0:
        return []

    rows = []
    with open(path, encoding="utf-8") as fh:
        for row in csv.reader(fh):
            if len(row) != 5:
                continue
            date = datetime.strptime(row[0], "%d/%m/%Y").date()
            home = N.historic_key(row[1].strip())
            away = N.historic_key(row[2].strip())
            if not home or not away:
                raise SystemExit(
                    f"unmapped current-season team in {fname}: {row[1]} / {row[2]}"
                )
            rows.append((date, home, away, int(row[3]), int(row[4])))
    rows.sort(key=lambda r: r[0])
    return rows


def build_table(matches):
    """Compute a league table from exactly the supplied season's matches."""
    rows = {}
    for _, home, away, hg, ag in matches:
        for team in (home, away):
            rows.setdefault(team, {
                "team": team, "p": 0, "w": 0, "d": 0, "l": 0,
                "gf": 0, "ga": 0, "pts": 0, "form": [],
            })
        hrow, arow = rows[home], rows[away]
        hrow["p"] += 1
        arow["p"] += 1
        hrow["gf"] += hg
        hrow["ga"] += ag
        arow["gf"] += ag
        arow["ga"] += hg
        if hg > ag:
            hrow["w"] += 1
            arow["l"] += 1
            hrow["pts"] += 3
            hrow["form"].append("W")
            arow["form"].append("L")
        elif hg < ag:
            arow["w"] += 1
            hrow["l"] += 1
            arow["pts"] += 3
            arow["form"].append("W")
            hrow["form"].append("L")
        else:
            hrow["d"] += 1
            arow["d"] += 1
            hrow["pts"] += 1
            arow["pts"] += 1
            hrow["form"].append("D")
            arow["form"].append("D")

    out = sorted(
        rows.values(),
        key=lambda r: (-r["pts"], -(r["gf"] - r["ga"]), -r["gf"], r["team"]),
    )
    for row in out:
        row["form"] = row["form"][-5:]
    return out


def current_tables():
    tables = {}
    for div in N.DIV_PRIMARY:
        matches = load_current_rows(div)
        euro, releg = ZONES.get(div, (0, 0))
        if not matches:
            tables[div] = {
                "rows": [], "asOf": None, "matches": 0,
                "euro": euro, "releg": releg, "recent": [],
            }
            continue

        last_date = matches[-1][0]
        recent = [m for m in matches if (last_date - m[0]).days <= 4]
        tables[div] = {
            "rows": build_table(matches),
            "asOf": last_date.isoformat(),
            "matches": len(matches),
            "euro": euro,
            "releg": releg,
            "recent": [
                {
                    "date": m[0].isoformat(), "home": m[1], "away": m[2],
                    "hg": m[3], "ag": m[4],
                }
                for m in recent[-10:]
            ],
        }
    return tables


def load_refresh_status():
    try:
        with open(STATUS_PATH, encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return {"runAt": None, "fixtures": {"state": "unknown", "lastSuccessfulFetch": None}}


def main():
    if not os.path.exists(PAYLOAD_PATH):
        raise SystemExit("data/payload.json is missing — run model/build.py first")

    with open(PAYLOAD_PATH, encoding="utf-8") as fh:
        payload = json.load(fh)

    tables = current_tables()
    payload["tables"] = tables
    payload["freshness"] = load_refresh_status()
    payload["freshness"]["currentTablesAsOf"] = {
        div: table["asOf"] for div, table in tables.items()
    }

    as_of = [table["asOf"] for table in tables.values() if table["asOf"]]
    payload["freshness"]["currentResultsAsOf"] = max(as_of) if as_of else None

    with open(PAYLOAD_PATH, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, separators=(",", ":"))

    print("finalized payload with current-season league tables")
    if payload["freshness"].get("fixtures", {}).get("state") == "cached":
        print("  ! fixture source degraded; last-known-good fixture file retained")


if __name__ == "__main__":
    main()
