"""
Team-name bridge between the two real sources.

  football-data.co.uk  ->  short names   ("Nott'm Forest", "Man United")
  openfootball         ->  long names    ("Nottingham Forest FC")

Only teams that actually appear in the fixture card need mapping. Anything
missing from the 2025/26 top flight is a promoted side and is handled by the
model's promoted-team prior, not by inventing a history for it.
"""

# fixture-card division code -> the historical files it may draw on,
# in priority order (a promoted English side is looked up in the Championship)
DIV_SOURCES = {
    "E0":  ["2025-26_en.1.csv", "2025-26_en.2.csv"],
    "E1":  ["2025-26_en.2.csv", "2025-26_en.1.csv"],
    "D1":  ["2025-26_de.1.csv"],
    "F1":  ["2025-26_fr.1.csv"],
    "N1":  ["2025-26_nl.1.csv"],
    "SP1": ["2025-26_sp.1.csv"],
    "I1":  ["2025-26_it.1.csv"],
    "USA": ["2025_usa1.csv"],
    "MEX": ["2025-26_mex1.csv"],
    "BRA": ["2025_bra1.csv"],
    "ARG": ["2025_arg1.csv"],
    "JPN": ["2025_jpn1.csv"],
}

# division code -> the file whose fitted strengths define that division's scale
DIV_PRIMARY = {
    "E0": "2025-26_en.1.csv", "E1": "2025-26_en.2.csv", "D1": "2025-26_de.1.csv",
    "F1": "2025-26_fr.1.csv", "N1": "2025-26_nl.1.csv",
    "SP1": "2025-26_sp.1.csv", "I1": "2025-26_it.1.csv",
    "USA": "2025_usa1.csv", "MEX": "2025-26_mex1.csv", "BRA": "2025_bra1.csv",
    "ARG": "2025_arg1.csv", "JPN": "2025_jpn1.csv",
}

# division code -> the fixed filename its current-season file lives at.
# build.py auto-discovers which of these actually exist rather than being
# told, so a season that hasn't kicked off yet (or a source that hasn't
# published it yet) needs no code change once real data shows up — the
# refresh script just writes the file and the next build picks it up.
CURRENT_STEM = {
    "E0": "cur_2627_E0.csv", "E1": "cur_2627_E1.csv", "D1": "cur_2627_D1.csv",
    "F1": "cur_2627_F1.csv", "N1": "cur_2627_N1.csv",
    "SP1": "cur_2627_SP1.csv", "I1": "cur_2627_I1.csv",
    "USA": "cur_2026_usa1.csv", "MEX": "cur_2627_mex1.csv",
    "BRA": "cur_2026_bra1.csv", "ARG": "cur_2026_arg1.csv",
    "JPN": "cur_2026_jpn1.csv",
}

DIV_META = {
    "E0":  ("Premier League", "England",     "en"),
    "E1":  ("Championship",   "England",     "en"),
    "D1":  ("Bundesliga",     "Germany",     "de"),
    "F1":  ("Ligue 1",        "France",      "fr"),
    "N1":  ("Eredivisie",     "Netherlands", "nl"),
    "SP1": ("La Liga",        "Spain",       "sp"),
    "I1":  ("Serie A",        "Italy",       "it"),
    "USA": ("MLS",            "USA",         "us"),
    "MEX": ("Liga MX",        "Mexico",      "mx"),
    "BRA": ("Série A",        "Brazil",      "br"),
    "ARG": ("Liga Profesional", "Argentina", "ar"),
    "JPN": ("J1 League",      "Japan",       "jp"),
}

# football-data.co.uk short name -> openfootball long name
ALIAS = {
    # --- England, top flight 2026/27 ---
    "Arsenal": "Arsenal FC",
    "Aston Villa": "Aston Villa FC",
    "Bournemouth": "AFC Bournemouth",
    "Brentford": "Brentford FC",
    "Brighton": "Brighton & Hove Albion FC",
    "Chelsea": "Chelsea FC",
    "Crystal Palace": "Crystal Palace FC",
    "Everton": "Everton FC",
    "Fulham": "Fulham FC",
    "Leeds": "Leeds United FC",
    "Liverpool": "Liverpool FC",
    "Man City": "Manchester City FC",
    "Man United": "Manchester United FC",
    "Newcastle": "Newcastle United FC",
    "Nott'm Forest": "Nottingham Forest FC",
    "Sunderland": "Sunderland AFC",
    "Tottenham": "Tottenham Hotspur FC",
    "West Ham": "West Ham United FC",
    "Wolves": "Wolverhampton Wanderers FC",
    "Burnley": "Burnley FC",
    # --- England, second tier ---
    "Birmingham": "Birmingham City FC",
    "Blackburn": "Blackburn Rovers FC",
    "Bristol City": "Bristol City FC",
    "Charlton": "Charlton Athletic FC",
    "Coventry": "Coventry City FC",
    "Derby": "Derby County FC",
    "Hull": "Hull City AFC",
    "Ipswich": "Ipswich Town FC",
    "Leicester": "Leicester City FC",
    "Middlesbrough": "Middlesbrough FC",
    "Millwall": "Millwall FC",
    "Norwich": "Norwich City FC",
    "Oxford": "Oxford United FC",
    "Portsmouth": "Portsmouth FC",
    "Preston": "Preston North End FC",
    "QPR": "Queens Park Rangers FC",
    "Sheffield United": "Sheffield United FC",
    "Sheffield Weds": "Sheffield Wednesday FC",
    "Southampton": "Southampton FC",
    "Stoke": "Stoke City FC",
    "Swansea": "Swansea City AFC",
    "Watford": "Watford FC",
    "West Brom": "West Bromwich Albion FC",
    "Wrexham": "Wrexham AFC",
    # --- Spain ---
    "Ath Bilbao": "Athletic Club",
    "Ath Madrid": "Club Atlético de Madrid",
    "Alaves": "Deportivo Alavés",
    "Barcelona": "FC Barcelona",
    "Betis": "Real Betis Balompié",
    "Celta": "RC Celta de Vigo",
    "Elche": "Elche CF",
    "Espanol": "RCD Espanyol de Barcelona",
    "Getafe": "Getafe CF",
    "Girona": "Girona FC",
    "Levante": "Levante UD",
    "Mallorca": "RCD Mallorca",
    "Osasuna": "CA Osasuna",
    "Oviedo": "Real Oviedo",
    "Real Madrid": "Real Madrid CF",
    "Sevilla": "Sevilla FC",
    "Sociedad": "Real Sociedad de Fútbol",
    "Valencia": "Valencia CF",
    "Vallecano": "Rayo Vallecano de Madrid",
    "Villarreal": "Villarreal CF",
    # football-data.co.uk changed its Spanish short-name convention between
    # the 2025/26 and 2026/27 files (Ath Madrid -> Atl. Madrid, Vallecano ->
    # Rayo Vallecano) — both spellings are kept, mapped to the same club, so
    # a team's history carries across the change rather than looking like
    # two different sides.
    "Atl. Madrid": "Club Atlético de Madrid",
    "Rayo Vallecano": "Rayo Vallecano de Madrid",
    # promoted into 2026/27 — no prior-season record in the top flight.
    # The fixture-odds feed and the results feed spell Deportivo differently
    # ("La Coruna" vs "Dep. A Coruna") — both point at the same club.
    "Dep. A Coruna": "Deportivo de La Coruña",
    "La Coruna": "Deportivo de La Coruña",
    "Santander": "Racing de Santander",
    "Malaga": "Málaga CF",
    # --- Italy ---
    "Atalanta": "Atalanta BC",
    "Bologna": "Bologna FC 1909",
    "Cagliari": "Cagliari Calcio",
    "Como": "Como 1907",
    "Cremonese": "US Cremonese",
    "Fiorentina": "ACF Fiorentina",
    "Genoa": "Genoa CFC",
    "Inter": "FC Internazionale Milano",
    "Juventus": "Juventus FC",
    "Lazio": "SS Lazio",
    "Lecce": "US Lecce",
    "Milan": "AC Milan",
    "Napoli": "SSC Napoli",
    "Parma": "Parma Calcio 1913",
    "Pisa": "AC Pisa 1909",
    "Roma": "AS Roma",
    "Sassuolo": "US Sassuolo Calcio",
    "Torino": "Torino FC",
    "Udinese": "Udinese Calcio",
    "Verona": "Hellas Verona FC",
    # --- Germany ---
    "Augsburg": "FC Augsburg",
    "Bayern Munich": "FC Bayern München",
    "Dortmund": "Borussia Dortmund",
    "Ein Frankfurt": "Eintracht Frankfurt",
    "Freiburg": "SC Freiburg",
    "Hamburg": "Hamburger SV",
    "Heidenheim": "1. FC Heidenheim 1846",
    "Hoffenheim": "TSG 1899 Hoffenheim",
    "FC Koln": "1. FC Köln",
    "Leverkusen": "Bayer 04 Leverkusen",
    "Mainz": "1. FSV Mainz 05",
    "M'gladbach": "Borussia Mönchengladbach",
    "RB Leipzig": "RB Leipzig",
    "St Pauli": "FC St. Pauli 1910",
    "Stuttgart": "VfB Stuttgart",
    "Union Berlin": "1. FC Union Berlin",
    "Werder Bremen": "SV Werder Bremen",
    "Wolfsburg": "VfL Wolfsburg",
    # --- France ---
    "Angers": "Angers SCO",
    "Auxerre": "AJ Auxerre",
    "Brest": "Stade Brestois 29",
    "Le Havre": "Le Havre AC",
    "Lens": "Racing Club de Lens",
    "Lille": "Lille OSC",
    "Lorient": "FC Lorient",
    "Lyon": "Olympique Lyonnais",
    "Marseille": "Olympique de Marseille",
    "Metz": "FC Metz",
    "Monaco": "AS Monaco FC",
    "Nantes": "FC Nantes",
    "Nice": "OGC Nice",
    "Paris FC": "Paris FC",
    "Paris SG": "Paris Saint-Germain FC",
    "Rennes": "Stade Rennais FC 1901",
    "Strasbourg": "RC Strasbourg Alsace",
    "Toulouse": "Toulouse FC",
    "Troyes": "ES Troyes AC",
    "Le Mans": "Le Mans FC",
    # --- Netherlands ---
    "Ajax": "AFC Ajax",
    "AZ Alkmaar": "AZ",
    "Excelsior": "SBV Excelsior",
    "Feyenoord": "Feyenoord Rotterdam",
    "For Sittard": "Fortuna Sittard",
    "Go Ahead Eagles": "Go Ahead Eagles",
    "Groningen": "FC Groningen",
    "Heerenveen": "SC Heerenveen",
    "Heracles": "Heracles Almelo",
    "NAC Breda": "NAC Breda",
    "Nijmegen": "NEC",
    "PSV Eindhoven": "PSV",
    "Sparta Rotterdam": "Sparta Rotterdam",
    "Telstar": "Telstar 1963",
    "Twente": "FC Twente '65",
    "Utrecht": "FC Utrecht",
    "Volendam": "FC Volendam",
    "Zwolle": "PEC Zwolle",
    # promoted into 2026/27 — no prior-season record in the top flight.
    # Long names matched exactly to openfootball's spelling, since that's
    # the join key this season's results are keyed on.
    "Willem II": "Willem II Tilburg",
    "Den Haag": "ADO Den Haag",
    "Cambuur": "SC Cambuur-Leeuwarden",
    "Lincoln": "Lincoln City FC",
    "Cardiff": "Cardiff City FC",
    "Bolton": "Bolton Wanderers FC",
    # --- backtest-only leagues ---------------------------------------
    # MLS, Liga MX, Brazil, Argentina and J1 League have no bookmaker-odds
    # feed for upcoming fixtures, so they never appear on the daily card —
    # only team strength and the walk-forward backtest. One source, one
    # naming convention, so short == long here; there's no separate
    # display form to bridge to.
    # --- MLS (USA) ---
    "Atlanta Utd": "Atlanta Utd",
    "Austin FC": "Austin FC",
    "CF Montreal": "CF Montreal",
    "Charlotte": "Charlotte",
    "Chicago Fire": "Chicago Fire",
    "Colorado Rapids": "Colorado Rapids",
    "Columbus Crew": "Columbus Crew",
    "DC United": "DC United",
    "FC Cincinnati": "FC Cincinnati",
    "FC Dallas": "FC Dallas",
    "Houston Dynamo": "Houston Dynamo",
    "Inter Miami": "Inter Miami",
    "Los Angeles FC": "Los Angeles FC",
    "Los Angeles Galaxy": "Los Angeles Galaxy",
    "Minnesota United": "Minnesota United",
    "Nashville SC": "Nashville SC",
    "New England Revolution": "New England Revolution",
    "New York City": "New York City",
    "New York Red Bulls": "New York Red Bulls",
    "Orlando City": "Orlando City",
    "Philadelphia Union": "Philadelphia Union",
    "Portland Timbers": "Portland Timbers",
    "Real Salt Lake": "Real Salt Lake",
    "San Diego FC": "San Diego FC",
    "San Jose Earthquakes": "San Jose Earthquakes",
    "Seattle Sounders": "Seattle Sounders",
    "Sporting Kansas City": "Sporting Kansas City",
    "St. Louis City": "St. Louis City",
    "Toronto FC": "Toronto FC",
    "Vancouver Whitecaps": "Vancouver Whitecaps",
    # --- Liga MX (Mexico) ---
    "Atl. San Luis": "Atl. San Luis",
    "Atlante": "Atlante",
    "Atlas": "Atlas",
    "Club America": "Club America",
    "Club Leon": "Club Leon",
    "Club Tijuana": "Club Tijuana",
    "Cruz Azul": "Cruz Azul",
    "Guadalajara Chivas": "Guadalajara Chivas",
    "Juarez": "Juarez",
    "Mazatlan FC": "Mazatlan FC",
    "Monterrey": "Monterrey",
    "Necaxa": "Necaxa",
    "Pachuca": "Pachuca",
    "Puebla": "Puebla",
    "Queretaro": "Queretaro",
    "Santos Laguna": "Santos Laguna",
    "Tigres UANL": "Tigres UANL",
    "Toluca": "Toluca",
    "UNAM Pumas": "UNAM Pumas",
    # --- Brasileirao Serie A (Brazil) ---
    "Athletico-PR": "Athletico-PR",
    "Atletico-MG": "Atletico-MG",
    "Bahia": "Bahia",
    "Botafogo RJ": "Botafogo RJ",
    "Bragantino": "Bragantino",
    "Ceara": "Ceara",
    "Chapecoense-SC": "Chapecoense-SC",
    "Corinthians": "Corinthians",
    "Coritiba": "Coritiba",
    "Cruzeiro": "Cruzeiro",
    "Flamengo RJ": "Flamengo RJ",
    "Fluminense": "Fluminense",
    "Fortaleza": "Fortaleza",
    "Gremio": "Gremio",
    "Internacional": "Internacional",
    "Juventude": "Juventude",
    "Mirassol": "Mirassol",
    "Palmeiras": "Palmeiras",
    "Remo": "Remo",
    "Santos": "Santos",
    "Sao Paulo": "Sao Paulo",
    "Sport Recife": "Sport Recife",
    "Vasco": "Vasco",
    "Vitoria": "Vitoria",
    # --- Liga Profesional (Argentina) ---
    "Aldosivi": "Aldosivi",
    "Argentinos Jrs": "Argentinos Jrs",
    "Atl. Tucuman": "Atl. Tucuman",
    "Banfield": "Banfield",
    "Barracas Central": "Barracas Central",
    "Belgrano": "Belgrano",
    "Boca Juniors": "Boca Juniors",
    "Central Cordoba": "Central Cordoba",
    "Defensa y Justicia": "Defensa y Justicia",
    "Dep. Riestra": "Dep. Riestra",
    "Estudiantes L.P.": "Estudiantes L.P.",
    "Estudiantes Rio Cuarto": "Estudiantes Rio Cuarto",
    "Gimnasia L.P.": "Gimnasia L.P.",
    "Gimnasia Mendoza": "Gimnasia Mendoza",
    "Godoy Cruz": "Godoy Cruz",
    "Huracan": "Huracan",
    "Ind. Rivadavia": "Ind. Rivadavia",
    "Independiente": "Independiente",
    "Instituto": "Instituto",
    "Lanus": "Lanus",
    "Newells Old Boys": "Newells Old Boys",
    "Platense": "Platense",
    "Racing Club": "Racing Club",
    "River Plate": "River Plate",
    "Rosario Central": "Rosario Central",
    "San Lorenzo": "San Lorenzo",
    "San Martin S.J.": "San Martin S.J.",
    "Sarmiento Junin": "Sarmiento Junin",
    "Talleres Cordoba": "Talleres Cordoba",
    "Tigre": "Tigre",
    "Union de Santa Fe": "Union de Santa Fe",
    "Velez Sarsfield": "Velez Sarsfield",
    # --- J1 League (Japan) ---
    "Albirex Niigata": "Albirex Niigata",
    "Avispa Fukuoka": "Avispa Fukuoka",
    "Cerezo Osaka": "Cerezo Osaka",
    "Chiba": "Chiba",
    "FC Tokyo": "FC Tokyo",
    "Gamba Osaka": "Gamba Osaka",
    "Kashima Antlers": "Kashima Antlers",
    "Kashiwa Reysol": "Kashiwa Reysol",
    "Kawasaki Frontale": "Kawasaki Frontale",
    "Kyoto": "Kyoto",
    "Machida": "Machida",
    "Mito": "Mito",
    "Nagoya Grampus": "Nagoya Grampus",
    "Okayama": "Okayama",
    "Sanfrecce Hiroshima": "Sanfrecce Hiroshima",
    "Shimizu S-Pulse": "Shimizu S-Pulse",
    "Shonan Bellmare": "Shonan Bellmare",
    "Urawa Reds": "Urawa Reds",
    "V-Varen Nagasaki": "V-Varen Nagasaki",
    "Verdy": "Verdy",
    "Vissel Kobe": "Vissel Kobe",
    "Yokohama F. Marinos": "Yokohama F. Marinos",
    "Yokohama FC": "Yokohama FC",
}

# How a club is shown in the interface. Anything absent keeps its short name.
DISPLAY = {
    "Nott'm Forest": "Nottingham Forest", "Man United": "Manchester United",
    "Man City": "Manchester City", "Sheffield Weds": "Sheffield Wednesday",
    "Ath Bilbao": "Athletic Club", "Ath Madrid": "Atlético Madrid", "Atl. Madrid": "Atlético Madrid",
    "Espanol": "Espanyol", "Vallecano": "Rayo Vallecano", "Sociedad": "Real Sociedad",
    "Dep. A Coruna": "Deportivo La Coruña", "La Coruna": "Deportivo La Coruña",
    "Santander": "Racing Santander", "Malaga": "Málaga",
    "Betis": "Real Betis", "Celta": "Celta Vigo", "Alaves": "Alavés",
    "Bayern Munich": "Bayern München", "Ein Frankfurt": "Eintracht Frankfurt",
    "FC Koln": "Köln", "M'gladbach": "Mönchengladbach", "St Pauli": "St. Pauli",
    "Paris SG": "Paris Saint-Germain", "For Sittard": "Fortuna Sittard",
    "AZ Alkmaar": "AZ", "PSV Eindhoven": "PSV", "Nijmegen": "NEC",
    "Den Haag": "ADO Den Haag", "Cambuur": "SC Cambuur", "Le Mans": "Le Mans FC",
    "Troyes": "ES Troyes AC", "Bolton": "Bolton Wanderers", "Lincoln": "Lincoln City",
    "Cardiff": "Cardiff City", "Monza": "AC Monza", "Frosinone": "Frosinone Calcio",
    "Venezia": "Venezia FC", "Coventry": "Coventry City", "Hull": "Hull City",
    "Ipswich": "Ipswich Town", "QPR": "Queens Park Rangers", "West Brom": "West Bromwich Albion",
    "Preston": "Preston North End", "Norwich": "Norwich City", "Derby": "Derby County",
    "Stoke": "Stoke City", "Swansea": "Swansea City", "Blackburn": "Blackburn Rovers",
    "Birmingham": "Birmingham City", "Charlton": "Charlton Athletic",
    "Leicester": "Leicester City", "Oxford": "Oxford United",
}

# Short label used in tight columns and market lines.
SHORT = {
    "Manchester United": "Man Utd", "Manchester City": "Man City",
    "Nottingham Forest": "Forest", "Tottenham": "Tottenham",
    "Wolverhampton Wanderers": "Wolves", "Crystal Palace": "Palace",
    "Sheffield Wednesday": "Sheff Wed", "Sheffield United": "Sheff Utd",
    "West Bromwich Albion": "West Brom", "Queens Park Rangers": "QPR",
    "Preston North End": "Preston", "Blackburn Rovers": "Blackburn",
    "Charlton Athletic": "Charlton", "Bolton Wanderers": "Bolton",
    "Atlético Madrid": "Atlético", "Real Sociedad": "Sociedad", "Real Betis": "Betis",
    "Athletic Club": "Athletic", "Rayo Vallecano": "Rayo", "Celta Vigo": "Celta",
    "Bayern München": "Bayern", "Eintracht Frankfurt": "Eintracht",
    "Mönchengladbach": "Gladbach", "Paris Saint-Germain": "PSG",
    "Fortuna Sittard": "Fortuna", "Go Ahead Eagles": "Go Ahead",
    "ADO Den Haag": "Den Haag", "SC Cambuur": "Cambuur", "Sparta Rotterdam": "Sparta",
    "Frosinone Calcio": "Frosinone", "Venezia FC": "Venezia", "AC Monza": "Monza",
    "Coventry City": "Coventry", "Hull City": "Hull", "Ipswich Town": "Ipswich",
    "Norwich City": "Norwich", "Derby County": "Derby", "Stoke City": "Stoke",
    "Swansea City": "Swansea", "Birmingham City": "Birmingham",
    "Leicester City": "Leicester", "Oxford United": "Oxford",
    "Lincoln City": "Lincoln", "Cardiff City": "Cardiff", "Bristol City": "Bristol City",
    "Le Mans FC": "Le Mans", "ES Troyes AC": "Troyes",
}


def display(short_name):
    return DISPLAY.get(short_name, short_name)


def short(display_name):
    return SHORT.get(display_name, display_name)


def historic_key(short_name):
    """openfootball name for a fixture-card team, or None if it has no history."""
    return ALIAS.get(short_name)
